const heroes = [
{name:"abaddon",gender:"male",race:"undead",role:"offlane",attr:"strength",complexity:1,attack:"melee",year:2011,img:"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/heroes/abaddon_full.png"},
{name:"alchemist",gender:"male",race:"goblin",role:"carry",attr:"strength",complexity:1,attack:"melee",year:2011,img:"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/heroes/alchemist_full.png"},
{name:"ancient apparition",gender:"male",race:"spirit",role:"support",attr:"intelligence",complexity:2,attack:"ranged",year:2011,img:"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/heroes/ancient_apparition_full.png"},
{name:"antimage",gender:"male",race:"human",role:"carry",attr:"agility",complexity:2,attack:"melee",year:2011,img:"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/heroes/antimage_full.png"},
{name:"axe",gender:"male",race:"orc",role:"offlane",attr:"strength",complexity:1,attack:"melee",year:2011,img:"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/heroes/axe_full.png"},
{name:"bane",gender:"male",race:"demon",role:"support",attr:"intelligence",complexity:2,attack:"ranged",year:2011,img:"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/heroes/bane_full.png"},
{name:"batrider",gender:"male",race:"human",role:"offlane",attr:"intelligence",complexity:3,attack:"ranged",year:2011,img:"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/heroes/batrider_full.png"},
{name:"beastmaster",gender:"male",race:"human",role:"offlane",attr:"strength",complexity:2,attack:"melee",year:2011,img:"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/heroes/beastmaster_full.png"},
{name:"bloodseeker",gender:"male",race:"human",role:"carry",attr:"agility",complexity:1,attack:"melee",year:2011,img:"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/heroes/bloodseeker_full.png"},
{name:"crystal maiden",gender:"female",race:"human",role:"hard support",attr:"intelligence",complexity:1,attack:"ranged",year:2011,img:"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/heroes/crystal_maiden_full.png"},
{name:"drow ranger",gender:"female",race:"undead",role:"carry",attr:"agility",complexity:1,attack:"ranged",year:2011,img:"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/heroes/drow_ranger_full.png"},
{name:"earthshaker",gender:"male",race:"beast",role:"offlane",attr:"strength",complexity:2,attack:"melee",year:2011,img:"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/heroes/earthshaker_full.png"},
{name:"juggernaut",gender:"male",race:"human",role:"carry",attr:"agility",complexity:1,attack:"melee",year:2011,img:"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/heroes/juggernaut_full.png"},
{name:"mirana",gender:"female",race:"elf",role:"support",attr:"agility",complexity:2,attack:"ranged",year:2011,img:"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/heroes/mirana_full.png"},
{name:"morphling",gender:"male",race:"water",role:"carry",attr:"agility",complexity:3,attack:"ranged",year:2011,img:"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/heroes/morphling_full.png"},
{name:"shadow fiend",gender:"male",race:"demon",role:"mid",attr:"agility",complexity:2,attack:"ranged",year:2011,img:"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/heroes/nevermore_full.png"},
{name:"phantom assassin",gender:"female",race:"human",role:"carry",attr:"agility",complexity:2,attack:"melee",year:2013,img:"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/heroes/phantom_assassin_full.png"},
{name:"pudge",gender:"male",race:"undead",role:"support",attr:"strength",complexity:1,attack:"melee",year:2013,img:"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/heroes/pudge_full.png"},
{name:"storm spirit",gender:"male",race:"spirit",role:"mid",attr:"intelligence",complexity:2,attack:"ranged",year:2011,img:"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/heroes/storm_spirit_full.png"},
{name:"invoker",gender:"male",race:"human",role:"mid",attr:"intelligence",complexity:3,attack:"ranged",year:2011,img:"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/heroes/invoker_full.png"},
{name:"lion",gender:"male",race:"demon",role:"support",attr:"intelligence",complexity:2,attack:"ranged",year:2011,img:"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/heroes/lion_full.png"},
{name:"witch doctor",gender:"male",race:"troll",role:"hard support",attr:"intelligence",complexity:1,attack:"ranged",year:2011,img:"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/heroes/witch_doctor_full.png"},
{name:"sniper",gender:"male",race:"dwarf",role:"carry",attr:"agility",complexity:1,attack:"ranged",year:2011,img:"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/heroes/sniper_full.png"},
{name:"templar assassin",gender:"female",race:"elf",role:"mid",attr:"agility",complexity:2,attack:"ranged",year:2011,img:"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/heroes/templar_assassin_full.png"},
{name:"zeus",gender:"male",race:"god",role:"mid",attr:"intelligence",complexity:1,attack:"ranged",year:2011,img:"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/heroes/zuus_full.png"}
];
